merge from main to teams branch
Azure-Samples/communication-services-android-calling-hero pull request #63
Opened 2021-06-07 07:24 UTC by iaulakh

## Purpose

* merge from main to teams branch

## Does this introduce a breaking change?

```
[x] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[x] Other... Please describe:
```

2021-06-07 07:25 UTC, iaulakh commented
@Gemakk @lpx1989 I noticed a strange dialog when I end call on this merge. may you please test?

2021-06-07 16:45 UTC, Gemakk commented
Do you mean this? 
![image](https://user-images.githubusercontent.com/6021109/121058320-1279b800-c775-11eb-8a0e-f4b2b3294f69.png)

2021-06-07 17:24 UTC, iaulakh commented
> Do you mean this?
> ![image](https://user-images.githubusercontent.com/6021109/121058320-1279b800-c775-11eb-8a0e-f4b2b3294f69.png)

yes this dialog appears when I click leave call

2021-06-09 17:48 UTC, Gemakk commented on AzureCalling/app/src/main/res/layout-land/activity_call.xml
> +            <include layout="@layout/floating_header_area" />
Looks like this element no longer shows up during Teams calls.  Specifically, the recording notifications.

2021-06-09 18:00 UTC, Gemakk requested changes
I'm unable to receive Recording notifications from Teams calls

2021-06-09 23:46 UTC, iaulakh commented
fixed merge issue, now we can see notification but :)
created bug @Gemakk : 
https://skype.visualstudio.com/SPOOL/_sprints/taskboard/Mobile%20UI/SPOOL/CY2021-Q2/Sprint%2038%20(Ends%20June%2013)?workitem=2476001

2021-06-10 19:36 UTC, Gemakk approved these changes
Tested

2021-06-10 23:41 UTC, lpx1989 approved these changes
Tested.

2021-06-10 23:45 UTC, merged