User/yukonchen/fix increase switch camera button touchable
Azure-Samples/communication-services-android-calling-hero pull request #80
Opened 2021-07-08 21:12 UTC by Gemakk

## Purpose

* Increases the touchable area for the switch camera button without increasing the icon size

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What to Check
Verify that the following are valid
* Switch Camera button functions as expected

2021-07-09 05:49 UTC, iaulakh reviewed
tested. I noticed that sometime while switching video was not flipped. may be because of bug https://github.com/Azure-Samples/communication-services-android-calling-hero/pull/79? @Gemakk

2021-07-09 17:32 UTC, Gemakk commented
> tested. I noticed that sometime while switching video was not flipped. may be because of bug #79? @Gemakk

Yes, if calls are involved.

2021-07-09 19:43 UTC, iaulakh approved these changes, later dismissed

2021-07-13 07:08 UTC, waynemo requested changes

2021-07-13 07:08 UTC, waynemo commented on AzureCalling/app/src/main/java/com/azure/samples/communication/calling/activities/SetupActivity.java
> +    private ImageButton switchCameraImage;
Instead of two overlapping buttons, could we have a single ImageButton or ImageView with padding around the icon?

2021-07-20 18:56 UTC, waynemo requested changes

2021-07-20 18:56 UTC, waynemo commented on AzureCalling/app/src/main/res/layout/activity_setup.xml
> +            </ImageButton>
Since the parent is a clickable view, this does not need to be an `ImageButton`. We can use `ImageView` instead.

2021-07-20 18:56 UTC, waynemo commented on AzureCalling/app/src/main/res/layout/participant_view.xml
> +            </ImageButton>
Since the parent is a clickable view, this does not need to be an ImageButton. We can use ImageView instead.

2021-07-26 19:03 UTC, waynemo approved these changes

2021-07-26 20:20 UTC, iaulakh approved these changes

2021-07-26 21:12 UTC, merged