bug/Fix Video Disappears when returning from "Add Participants"
Azure-Samples/communication-services-android-calling-hero pull request #91
Opened 2021-11-09 20:28 UTC by ShaunaSong

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
Start new call
Enter name
Start call
Turn on video
Add participant
swipe to cancel adding participant
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2021-11-09 20:54 UTC, lpx1989 commented
Tested the fix.

2021-11-09 20:55 UTC, lpx1989 submitted a review, later dismissed

2021-11-10 06:59 UTC, phileo99 requested changes

2021-11-10 06:59 UTC, phileo99 commented on AzureCalling/app/src/main/java/com/azure/samples/communication/calling/activities/CallActivity.java
> +        callingContext.pauseVideo().thenRun(() -> runOnUiThread(() ->
For the scenario where both `onPause()` and `onStop()` is both called, `callingContext.pauseVideo()` will be called 2x.
Is there a way to detect when `callingContext.pauseVideo()` has already been called ?

2021-11-10 22:12 UTC, phileo99 approved these changes
Tested dismissing the add participants bottom sheet dialog, and video remains showing
👍

2021-11-16 01:00 UTC, jamchengms approved these changes

2021-11-18 01:25 UTC, iaulakh approved these changes

2021-11-24 02:34 UTC, merged